name: Publish APIs for Team A

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - 'apimartifacts/apis/**'

  workflow_dispatch:
    inputs:
      COMMIT_ID_CHOICE:
        description: 'Publish mode'
        required: true
        type: choice
        default: "publish-artifacts-in-last-commit"
        options:
          - "publish-artifacts-in-last-commit"
          - "publish-all-artifacts-in-repo"

jobs:
  get-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Set commit ID
        id: commit
        run: echo "commit_id=${GITHUB_SHA}" >> $GITHUB_ENV
    outputs:
      commit_id: ${{ steps.commit.outputs.commit_id }}

  Push-Changes-To-APIM-Dev:
    needs: get-commit
    uses: ./.github/workflows/run-publisher-with-env.yaml
    with:
      API_MANAGEMENT_ENVIRONMENT: dev
      COMMIT_ID: ${{ needs.get-commit.outputs.commit_id }}
      API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: apimartifacts
    secrets: inherit
